name: tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    strategy:
      matrix:
        go: ["1.22", "1.23.5"]
        platform: [ubuntu-latest, windows-latest, macos-latest]

    # Workaround: https://github.com/actions/setup-go/issues/519
    env:
      GOTOOLCHAIN: local

    runs-on: ${{ matrix.platform }}

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go ${{ matrix.go }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}

      - name: Show Go go-version
        run: go version

      - name: Tests
        run: go test ./... -tags=tests
